version: '2'

services:
  dev:
    image: kubeless-ui-dev
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "yarn install && npm rebuild node-sass && yarn run dev"
    environment:
      NODE_ENV: development
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - "3000:3000"
