version: '2'
services:
  dev:
    image: kubeless-ui-dev
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "yarn install && npm rebuild node-sass && yarn run dev"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
